//! Flow Language - An LLM-optimized programming language
//! 
//! Flow is designed to be easily understood and generated by Large Language Models
//! while maintaining expressiveness and safety.

pub mod lexer;
pub mod parser;
pub mod types;
pub mod runtime;
pub mod interpreter;
pub mod ffi;
pub mod testing;

pub use lexer::Lexer;
pub use parser::Parser;
pub use interpreter::Interpreter;

#[derive(Debug, thiserror::Error)]
pub enum FlowError {
    #[error("Lexer error: {0}")]
    Lexer(#[from] lexer::LexerError),
    
    #[error("Parser error: {0}")]
    Parser(#[from] parser::ParserError),
    
    #[error("Type error: {0}")]
    Type(#[from] types::TypeError),
    
    #[error("Runtime error: {0}")]
    Runtime(#[from] runtime::RuntimeError),
    
    #[error("FFI error: {0}")]
    Ffi(#[from] ffi::FfiError),
}

pub type Result<T> = std::result::Result<T, FlowError>;